image: alpine:latest
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp *.html .public/
    - cp -r css .public/
    - mv .public public
artifacts:
  paths:
    - public
  only:
    - master
