    <div class="tip"> The <code>\e</code> (or <code>\edit</code>) will open the current querry buffer
	into the default editor (or the editor set by the <code>PSQL_EDITOR</code>, the
	  <code>EDITOR</code> or the <code>VISUAL</code> variables.<br/><br/>

	If none of those variables are set, the default editor is <code>vi</code> on Unix systems
   	and <code>notepad.exe</code> under Windows. <br/><br/ >
	This feature is available since at least Postgres 7.1 for Unix system and
	since Postgres run under Windows for Windows version.
	</div>
