    <div class="tip">The <code> \ef function linenumber</code> metacommand will open the <code>create or
	replace function</code> (or <code>create or replace procedure</code>) containing the code of
	the function (or procedure) you named and will position the cursor directly
	to the line number specified.
	  <script id="asciicast-434945" src="https://asciinema.org/a/434945.js" data-rows="20"
	  async></script>
      This feature is available since Postgres 9.1. Procedures were added with Postgres 11.
	</div>
