    <div class="tip">The <code> \ef function</code> metacommand will open the <code>create or
	replace function</code> (or <code>create or replace procedure</code>) containing the code of
	the function (or procedure) you named.<br/><br/>
	If no function name is specified, a <code>create function</code> template is created.
	<script id="asciicast-434932" src="https://asciinema.org/a/434932.js" data-rows="20"
	async></script>
      This feature is available
since Postgres 9.1. Procedures were added with Postgres 11.
	</div>
