    <div class="tip">The <code> \ev view</code> metacommand will open the <code>create or
	replace view</code> containing the SQL code of
	the view you named.<br/><br/>
	If no view name is specified, a <code>create view</code> template is created.
	  <script id="asciicast-435824" src="https://asciinema.org/a/435824.js" data-rows="20"
	  async></script>
      This feature is available since Postgres 9.6.
	</div>
