    <div class="tip">The <code> \ev view linenumber</code> metacommand will open the <code>create or
	replace view</code> containing the code of the view you named and will position the cursor directly
	to the line number specified.
	  <script id="asciicast-435826" src="https://asciinema.org/a/435826.js" data-rows="20"
	  async></script>
      This feature is available since Postgres 9.6.
	</div>
