    <div class="breath">
      See <a href=
      "https://www.postgresql.org/docs/current/app-psql.html">Postgres
      documentation</a> for more information.
    </div><a href="#" class="myButton" onclick=
    "pickATip();">Try a new tip</a><a href="psql_tips_all.html" class="myButton"
    >See them all</a>
  </main>
  <footer>
    <p>Theme inspired by <a href=
    "https://github.com/calintat/minimal">Minimal</a></p>
  </footer>
</body>
</html>

